### ISSUE TITLE
Formatting hint

### ISSUE THREAD

**Issue by vitaly-t** [davidbarsky/tangerine#1]
On your code:

``` js
authenticateUser(userID, hashedToken) {
        return this.db.one(
            `SELECT *
             FROM users AS A, hashed_tokens AS B
             WHERE A.user_id = B.user_id
             AND A.user_id = $1
             AND B.hashed_fb_token = $2`
             , userID
             , hashedToken)
    }
```

when passing in more than one formatting value, it must be an array: `[userID, hashedToken]`.

;)

**Comment by davidbarsky** [comment]
Huh. Thanks for the catch!

Really enjoying the library, thanks! :smile:

**Comment by vitaly-t** [comment]
In case you care to know how many records are actually deleted:

``` js
deleteUser(userID) {
        return this.db.none('DELETE FROM users WHERE user_id = $1', userID)
    }
```

it can be done by changing the code to:

``` js
deleteUser(userID)
{
    return this.db.result('DELETE FROM users WHERE user_id = $1', userID)
        .then(result=> result.rowCount);
}
```

**Comment by davidbarsky** [comment]
thanks a lot for your help, @vitaly-t! it's really nice of you to audit my (admittedly) crappy code. :smile:

**Comment by vitaly-t** [comment]
GitHub search is good to see all the most recent uses of the library, so it is often fun to poke people about that :)

**Comment by davidbarsky** [comment]
makes sense. enjoy your new year! 🎊
